name: SmartMoodle
description: Aplicativo para auxiliar usuários do moodle através de tecnologuas persuasivas.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.5+6
  http: ^0.12.0+2
  shared_preferences: ^0.5.4+6 
  rflutter_alert: ^1.0.3
  flutter_form_builder:
  sqflite: ^1.1.7+3
  mobx: 0.3.9+3
  flutter_mobx: ^0.3.3+3
  flutter_local_notifications: ^0.8.4+3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 0.3.10+1
  build_runner:
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/imgs/

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/logo_icon.png"