name: SmartMoodle
description: Aplicativo para auxiliar usuários do moodle através de tecnologuas persuasivas.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+6
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.5+6
  http: ^0.12.0+2
  shared_preferences: ^0.5.4+6 
  rflutter_alert: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/imgs/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_icon.png"